### PR TITLE
fix: unblock release builds, green the backend suite, gate biometric storage

### PR DESCRIPTION
**Pull request by arogan178**
Three follow-ups to #154, each independent.

### 1. Release builds could not run (`82b7ea56`)

`verifyReleaseCapacitorConfig` read `capConfig.hostname`, but `cap sync` writes those fields under `server`. Both lookups resolved to `null`, so the guard threw on *every* `assembleRelease`/`bundleRelease` claiming a dev profile was synced, regardless of what was actually there. Reads `server.hostname` / `server.cleartext` now.

This is the one that blocks shipping — no release AAB could be built off `master`.

### 2. Backend suite is green for the first time (`4f1736a2`)

Bun's `mock.module`/`vi.mock` replaces a module process-wide and never unwinds it, so a partial stub in one file strips exports from every file that runs later. Three cases had accumulated:

- `user.integration.test.ts` and `clerk-guards.test.ts` each replaced the whole `subscription-service` module with a one-method object, costing later files the other seven statics. That is what broke all nine `Play account token` tests — they passed in isolation. Both now spread the real module and subclass `SubscriptionService`.
- `profile-analytics.test.ts` stubbed the sync `eventBus` without ever asserting on it; the stub lacked `subscribeUserSync`, so `eventBus.test.ts` got a no-op publish. Removed — it is an in-memory `EventEmitter` with nothing worth stubbing.
- `product-analytics.test.ts` used `vi.stubGlobal`/`unstubAllGlobals`, which Bun's vitest shim does not implement.

`469 pass / 0 fail`, up from `456/13`. Note four of those failures predate #154 (`427/4` at `9161e3c4`), so this also clears a baseline that was already red.

### 3. Biometric storage is opt-in (`289db7a7`)

Both sign-in forms called `saveBiometricCredentials` unconditionally, writing the user's password to the Keychain/KeyStore on every password sign-in. `clearBiometricCredentials` existed but had no callers, so it also survived sign-out forever.

Adds a native-only opt-in checkbox defaulting to off, and clears the credential in both `useLogout` paths.

The stored secret is still the password rather than a revocable token — which is also what Clerk's own Expo `useLocalCredentials` stores. Passkeys would remove it entirely, but need `assetlinks.json` hosted first (it currently 404s), so that stays a follow-up.

### Verification

| Check | Result |
|---|---|
| Backend tests | 469 pass / 0 fail |
| Frontend tests | 851 pass / 0 fail |
| Typecheck (both) | clean |
| Lint | 0 errors |
| UI budgets | 16/16 |

### CODE REVIEW

**Comment by arogan178** [comment]
Pushed four more commits working through the remaining audit items.

### `946f54df` — SSE now uses a one-time ticket

`POST /api/sync/ticket` is an ordinary authenticated call that mints a random 32-byte ticket bound to the caller's session token, valid 30s and one redemption. `readSessionTokenFromRequest` exchanges `?ticket=` on `/api/sync/events` only and no longer accepts `?token=` anywhere. Redemption deletes the entry even when expired, so a value scraped from a proxy log can't be retried.

Only local auth mode ever used the query credential — Clerk mode authenticates the stream with cookies and skips the ticket request, so it's unchanged.

### `ef223947` — assetlinks.json now ships from this repo

I was wrong earlier that this needed the infra repo. `frontend/public/` **is** the production docroot: `/robots.txt`, `/icon.svg` and `/sitemap.xml` all serve 200 from it with correct content types and no redirects, via Cloudflare. The infra repo only holds DNS for the domain.

The file is in place plus `bun run verify:assetlinks`. **The fingerprint is still a placeholder** — it has to come from Play Console → Setup → App signing, and with Play App Signing that's Google's cert, not your upload key. That's the one thing I can't supply.

### `e6b631e2` — R8 rules staged, still off

`proguard-rules.pro` was the stock Android template, so enabling `minifyEnabled` would have stripped every reflectively-resolved Capacitor plugin. Real rules are now written (bridge, `@CapacitorPlugin`, `@PluginMethod`, both registered plugins, Cordova shim, `JavascriptInterface`).

Left **off** deliberately: R8 breakage in a Capacitor app never appears at build time, only as a feature that silently does nothing at runtime, and there's no Android SDK in this environment to produce a signed build to test. `docs/android-release-build.md` lists exactly what to exercise on device before flipping it.

### `6414a442` — google-auth pinned exactly

`^3.4.0-rc.4` was a caret range over a prerelease. npm's `latest` points at that same RC from May 2024, and the repo was last pushed January 2025 with 135 issues open — the range bought no fixes while leaving the version free to move.

### Deliberately not changed: register 409

De-enumerating registration properly means moving to verification-first signup — new users would stop being logged in after registering. That's a product decision, not a cleanup, and the exposure is bounded: `/api/auth/register` is rate-limited to 20 requests per 15 minutes, and production runs `VITE_AUTH_MODE=clerk`, so these local routes aren't reachable there at all. Flagging rather than deciding it unilaterally.

### Verification

| Check | Result |
|---|---|
| Backend tests | 478 pass / 0 fail |
| Frontend tests | 851 pass / 0 fail |
| Typecheck (both) | clean |
| Lint | 0 errors |
| UI budgets | 16/16 |

**Comment by arogan178** [comment]
**Correction — the test-isolation commit was wrong and is reverted (`229bd5e2`).**

I diagnosed the "13 failing backend tests" by running `bun test`. The backend's test script is `vitest run`, which is what CI executes and what this repo supports. Vitest scopes and hoists `vi.mock` per file, so the cross-file mock pollution I described never existed there.

Two claims in my earlier comment and in the commit message were therefore false:

- **"Master is red / 9 new failures from #154."** It wasn't. #154's CI run passed, and master has been green throughout.
- **"4 pre-existing failures predate #154."** Also an artifact of the wrong runner — `vi.stubGlobal` is unimplemented in Bun's shim but works fine in vitest.

Worse, the change broke the real suite: a top-level import referenced inside a `vi.mock` factory throws `Cannot access '__vi_import_0__' before initialization`, because vitest hoists the factory above the imports. Rewriting against `importOriginal` fixes vitest but then fails under `bun test`, which has no such argument — the two runners can't both be satisfied, and only one of them is real.

Reverted. Backend is back to 45 files / 453 tests passing, and CI is green.

The other four commits stand on their own and are unaffected: the release-config guard fix, the SSE ticket, assetlinks, R8 rules, and the dependency pin were all verified against vitest and the frontend suite.
